import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader, SiteFooter } from "@/components/site-chrome";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Roovr" },
      { name: "description", content: "Roovr Terms of Service. Reports are advisory only and AI-generated." },
      { property: "og:title", content: "Terms of Service — Roovr" },
      { property: "og:description", content: "Roovr Terms of Service. Reports are advisory only and AI-generated." },
    ],
  }),
  component: TermsPage,
});

function Section({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 style={{ fontSize: 20, fontWeight: 500, color: "#1A1108", letterSpacing: "-0.4px" }}>
        {n}. {title}
      </h2>
      <div className="mt-3 max-w-2xl" style={{ fontSize: 15, color: "#5F5E5A", lineHeight: 1.7 }}>
        {children}
      </div>
    </section>
  );
}

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col" style={{ background: "#FFFDF9" }}>
      <SiteHeader />
      <main className="mx-auto w-full max-w-3xl px-8 py-20 flex-1">
        <h1 style={{ fontSize: 40, fontWeight: 500, color: "#1A1108", letterSpacing: "-1.5px", lineHeight: 1.15 }}>
          Terms of Service
        </h1>
        <p className="mt-3" style={{ fontSize: 13, color: "#888780" }}>Last updated: 14 May 2026</p>

        <Section n={1} title="What Roovr provides">
          Roovr provides AI-generated property analysis reports. All reports are advisory only and do not constitute financial, legal, or surveying advice.
        </Section>
        <Section n={2} title="No liability">
          Roovr accepts no liability for decisions made based on report content. Always seek independent professional advice before making any property purchase decision.
        </Section>
        <Section n={3} title="Accuracy">
          Reports are generated by AI and may contain errors or omissions. Data is sourced from listing descriptions and publicly available information. Always verify independently.
        </Section>
        <Section n={4} title="Payments and refunds">
          All payments are one-time and non-refundable once a report has been accessed. If you have not accessed your report, contact{" "}
          <a href="mailto:hello@roovr.co" style={{ color: "#D85A30" }} className="hover:underline">hello@roovr.co</a>{" "}
          within 24 hours to request a refund.
        </Section>
        <Section n={5} title="Acceptable use">
          Roovr is for personal property research only. Reselling or redistributing reports is prohibited.
        </Section>
        <Section n={6} title="Buyer Pass expiry">
          Buyer Pass access expires 90 days after purchase. No automatic renewals. Renew at any time for £24.99.
        </Section>
        <Section n={7} title="Governing law">
          These terms are governed by the laws of England and Wales.
        </Section>
        <Section n={8} title="Contact">
          <a href="mailto:hello@roovr.co" style={{ color: "#D85A30" }} className="hover:underline">hello@roovr.co</a>
        </Section>
      </main>
      <SiteFooter />
    </div>
  );
}
