import { createFileRoute } from "@tanstack/react-router";
import { SiteHeader, SiteFooter } from "@/components/site-chrome";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — vett" },
      { name: "description", content: "vett Terms of Service. Reports are advisory only and AI-generated." },
      { property: "og:title", content: "Terms of Service — vett" },
      { property: "og:description", content: "vett Terms of Service. Reports are advisory only and AI-generated." },
    ],
  }),
  component: TermsPage,
});

const HEADING = "'Playfair Display', Georgia, serif";

function Section({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 style={{ fontFamily: HEADING, fontWeight: 400, fontSize: 24, color: "#1A1108", letterSpacing: "-0.3px" }}>
        {n}. {title}
      </h2>
      <div className="mt-3 max-w-2xl" style={{ fontSize: 15, fontWeight: 300, color: "#5F5E5A", lineHeight: 1.75 }}>
        {children}
      </div>
    </section>
  );
}

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col" style={{ background: "#F1EFE8" }}>
      <SiteHeader />
      <main className="mx-auto w-full max-w-3xl px-6 sm:px-8 py-16 sm:py-20 flex-1">
        <div
          className="p-8 sm:p-12"
          style={{ background: "#FFFDF9", border: "0.5px solid rgba(26,17,8,0.1)", borderRadius: 16 }}
        >
        <h1 style={{ fontFamily: HEADING, fontWeight: 400, fontSize: 44, color: "#1A1108", letterSpacing: "-0.8px", lineHeight: 1.1 }}>
          Terms of Service
        </h1>
        <p className="mt-3" style={{ fontSize: 13, fontWeight: 300, color: "#888780" }}>Last updated: 14 May 2026</p>

        <Section n={1} title="What vett provides">
          vett provides AI-generated property analysis reports to help UK home buyers research properties. Reports are informational only.
        </Section>
        <Section n={2} title="AI-generated content disclaimer">
          All report content generated by vett is AI-powered and advisory only. It does not constitute professional property, legal, financial, or surveying advice. Always seek independent professional advice before making any property purchase decision.
        </Section>
        <Section n={3} title="Acceptable use">
          vett is intended for individual home buyers researching properties for personal use. Commercial use of report data for investment analysis, resale, or bulk property research requires prior written consent from vett.
        </Section>
        <Section n={4} title="Refund policy">
          As reports are generated instantly using AI and third-party data services, we are unable to offer refunds once a report has been generated. If a technical fault on our part prevented you from accessing a paid report, contact{" "}
          <a href="mailto:support@roovr.co" style={{ color: "#2D6A4F" }} className="hover:underline">support@roovr.co</a>{" "}
          and we will resolve it.
        </Section>
        <Section n={5} title="Buyer Pass expiry">
          Buyer Pass access expires 90 days after purchase. There are no automatic renewals. We will send you a reminder email 7 days before your pass expires, and again the day before, giving you the option to purchase a new 90-day Buyer Pass for £24.99 or move to a monthly subscription at £7.99 per month. Nothing renews without your explicit action.
        </Section>
        <Section n={6} title="Service availability">
          We aim to maintain high availability but cannot guarantee uninterrupted service. We are not liable for losses arising from service downtime or analysis failures.
        </Section>
        <Section n={7} title="Limitation of liability">
          vett is not liable for any decisions made based on report content. Reports are provided as informational tools only. Our maximum liability in any circumstance is limited to the amount paid for the report in question.
        </Section>
        <Section n={8} title="Governing law">
          These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
        </Section>
        <Section n={9} title="Contact">
          <a href="mailto:support@roovr.co" style={{ color: "#2D6A4F" }} className="hover:underline">support@roovr.co</a>
        </Section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
