/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as MyReportRouteImport } from './routes/my-report'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BuyerLoginRouteImport } from './routes/buyer-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsStampDutyRouteImport } from './routes/tools/stamp-duty'
import { Route as ToolsRenovationCalculatorRouteImport } from './routes/tools/renovation-calculator'
import { Route as ToolsLocalBusinessesRouteImport } from './routes/tools/local-businesses'
import { Route as ReportTokenRouteImport } from './routes/report.$token'
import { Route as BlogHowToAnalyseARightmoveListingRouteImport } from './routes/blog/how-to-analyse-a-rightmove-listing'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiRenovationEstimateEmailRouteImport } from './routes/api/renovation-estimate-email'
import { Route as ApiPlaceReviewsRouteImport } from './routes/api/place-reviews'
import { Route as ApiLocalBusinessesRouteImport } from './routes/api/local-businesses'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCronCheckExpiryRemindersRouteImport } from './routes/api/public/cron/check-expiry-reminders'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportRoute = MyReportRouteImport.update({
  id: '/my-report',
  path: '/my-report',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerLoginRoute = BuyerLoginRouteImport.update({
  id: '/buyer-login',
  path: '/buyer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsStampDutyRoute = ToolsStampDutyRouteImport.update({
  id: '/tools/stamp-duty',
  path: '/tools/stamp-duty',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRenovationCalculatorRoute =
  ToolsRenovationCalculatorRouteImport.update({
    id: '/tools/renovation-calculator',
    path: '/tools/renovation-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsLocalBusinessesRoute = ToolsLocalBusinessesRouteImport.update({
  id: '/tools/local-businesses',
  path: '/tools/local-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTokenRoute = ReportTokenRouteImport.update({
  id: '/report/$token',
  path: '/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToAnalyseARightmoveListingRoute =
  BlogHowToAnalyseARightmoveListingRouteImport.update({
    id: '/blog/how-to-analyse-a-rightmove-listing',
    path: '/blog/how-to-analyse-a-rightmove-listing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenovationEstimateEmailRoute =
  ApiRenovationEstimateEmailRouteImport.update({
    id: '/api/renovation-estimate-email',
    path: '/api/renovation-estimate-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlaceReviewsRoute = ApiPlaceReviewsRouteImport.update({
  id: '/api/place-reviews',
  path: '/api/place-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocalBusinessesRoute = ApiLocalBusinessesRouteImport.update({
  id: '/api/local-businesses',
  path: '/api/local-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCheckExpiryRemindersRoute =
  ApiPublicCronCheckExpiryRemindersRouteImport.update({
    id: '/api/public/cron/check-expiry-reminders',
    path: '/api/public/cron/check-expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer-login': typeof BuyerLoginRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/my-report': typeof MyReportRoute
  '/my-reports': typeof MyReportsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/local-businesses': typeof ApiLocalBusinessesRoute
  '/api/place-reviews': typeof ApiPlaceReviewsRoute
  '/api/renovation-estimate-email': typeof ApiRenovationEstimateEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-analyse-a-rightmove-listing': typeof BlogHowToAnalyseARightmoveListingRoute
  '/report/$token': typeof ReportTokenRoute
  '/tools/local-businesses': typeof ToolsLocalBusinessesRoute
  '/tools/renovation-calculator': typeof ToolsRenovationCalculatorRoute
  '/tools/stamp-duty': typeof ToolsStampDutyRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/public/cron/check-expiry-reminders': typeof ApiPublicCronCheckExpiryRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer-login': typeof BuyerLoginRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/my-report': typeof MyReportRoute
  '/my-reports': typeof MyReportsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/local-businesses': typeof ApiLocalBusinessesRoute
  '/api/place-reviews': typeof ApiPlaceReviewsRoute
  '/api/renovation-estimate-email': typeof ApiRenovationEstimateEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-analyse-a-rightmove-listing': typeof BlogHowToAnalyseARightmoveListingRoute
  '/report/$token': typeof ReportTokenRoute
  '/tools/local-businesses': typeof ToolsLocalBusinessesRoute
  '/tools/renovation-calculator': typeof ToolsRenovationCalculatorRoute
  '/tools/stamp-duty': typeof ToolsStampDutyRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/public/cron/check-expiry-reminders': typeof ApiPublicCronCheckExpiryRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyer-login': typeof BuyerLoginRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/my-report': typeof MyReportRoute
  '/my-reports': typeof MyReportsRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/local-businesses': typeof ApiLocalBusinessesRoute
  '/api/place-reviews': typeof ApiPlaceReviewsRoute
  '/api/renovation-estimate-email': typeof ApiRenovationEstimateEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/how-to-analyse-a-rightmove-listing': typeof BlogHowToAnalyseARightmoveListingRoute
  '/report/$token': typeof ReportTokenRoute
  '/tools/local-businesses': typeof ToolsLocalBusinessesRoute
  '/tools/renovation-calculator': typeof ToolsRenovationCalculatorRoute
  '/tools/stamp-duty': typeof ToolsStampDutyRoute
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/public/cron/check-expiry-reminders': typeof ApiPublicCronCheckExpiryRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buyer-login'
    | '/compare'
    | '/dashboard'
    | '/faq'
    | '/my-report'
    | '/my-reports'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/results'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/api/local-businesses'
    | '/api/place-reviews'
    | '/api/renovation-estimate-email'
    | '/blog/$slug'
    | '/blog/how-to-analyse-a-rightmove-listing'
    | '/report/$token'
    | '/tools/local-businesses'
    | '/tools/renovation-calculator'
    | '/tools/stamp-duty'
    | '/blog/'
    | '/tools/'
    | '/api/public/cron/check-expiry-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buyer-login'
    | '/compare'
    | '/dashboard'
    | '/faq'
    | '/my-report'
    | '/my-reports'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/results'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/api/local-businesses'
    | '/api/place-reviews'
    | '/api/renovation-estimate-email'
    | '/blog/$slug'
    | '/blog/how-to-analyse-a-rightmove-listing'
    | '/report/$token'
    | '/tools/local-businesses'
    | '/tools/renovation-calculator'
    | '/tools/stamp-duty'
    | '/blog'
    | '/tools'
    | '/api/public/cron/check-expiry-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buyer-login'
    | '/compare'
    | '/dashboard'
    | '/faq'
    | '/my-report'
    | '/my-reports'
    | '/payment-success'
    | '/pricing'
    | '/privacy'
    | '/results'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/api/local-businesses'
    | '/api/place-reviews'
    | '/api/renovation-estimate-email'
    | '/blog/$slug'
    | '/blog/how-to-analyse-a-rightmove-listing'
    | '/report/$token'
    | '/tools/local-businesses'
    | '/tools/renovation-calculator'
    | '/tools/stamp-duty'
    | '/blog/'
    | '/tools/'
    | '/api/public/cron/check-expiry-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuyerLoginRoute: typeof BuyerLoginRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  MyReportRoute: typeof MyReportRoute
  MyReportsRoute: typeof MyReportsRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiLocalBusinessesRoute: typeof ApiLocalBusinessesRoute
  ApiPlaceReviewsRoute: typeof ApiPlaceReviewsRoute
  ApiRenovationEstimateEmailRoute: typeof ApiRenovationEstimateEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogHowToAnalyseARightmoveListingRoute: typeof BlogHowToAnalyseARightmoveListingRoute
  ReportTokenRoute: typeof ReportTokenRoute
  ToolsLocalBusinessesRoute: typeof ToolsLocalBusinessesRoute
  ToolsRenovationCalculatorRoute: typeof ToolsRenovationCalculatorRoute
  ToolsStampDutyRoute: typeof ToolsStampDutyRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiPublicCronCheckExpiryRemindersRoute: typeof ApiPublicCronCheckExpiryRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-report': {
      id: '/my-report'
      path: '/my-report'
      fullPath: '/my-report'
      preLoaderRoute: typeof MyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-login': {
      id: '/buyer-login'
      path: '/buyer-login'
      fullPath: '/buyer-login'
      preLoaderRoute: typeof BuyerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/stamp-duty': {
      id: '/tools/stamp-duty'
      path: '/tools/stamp-duty'
      fullPath: '/tools/stamp-duty'
      preLoaderRoute: typeof ToolsStampDutyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/renovation-calculator': {
      id: '/tools/renovation-calculator'
      path: '/tools/renovation-calculator'
      fullPath: '/tools/renovation-calculator'
      preLoaderRoute: typeof ToolsRenovationCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/local-businesses': {
      id: '/tools/local-businesses'
      path: '/tools/local-businesses'
      fullPath: '/tools/local-businesses'
      preLoaderRoute: typeof ToolsLocalBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$token': {
      id: '/report/$token'
      path: '/report/$token'
      fullPath: '/report/$token'
      preLoaderRoute: typeof ReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-analyse-a-rightmove-listing': {
      id: '/blog/how-to-analyse-a-rightmove-listing'
      path: '/blog/how-to-analyse-a-rightmove-listing'
      fullPath: '/blog/how-to-analyse-a-rightmove-listing'
      preLoaderRoute: typeof BlogHowToAnalyseARightmoveListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/renovation-estimate-email': {
      id: '/api/renovation-estimate-email'
      path: '/api/renovation-estimate-email'
      fullPath: '/api/renovation-estimate-email'
      preLoaderRoute: typeof ApiRenovationEstimateEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-reviews': {
      id: '/api/place-reviews'
      path: '/api/place-reviews'
      fullPath: '/api/place-reviews'
      preLoaderRoute: typeof ApiPlaceReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/local-businesses': {
      id: '/api/local-businesses'
      path: '/api/local-businesses'
      fullPath: '/api/local-businesses'
      preLoaderRoute: typeof ApiLocalBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/check-expiry-reminders': {
      id: '/api/public/cron/check-expiry-reminders'
      path: '/api/public/cron/check-expiry-reminders'
      fullPath: '/api/public/cron/check-expiry-reminders'
      preLoaderRoute: typeof ApiPublicCronCheckExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuyerLoginRoute: BuyerLoginRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  MyReportRoute: MyReportRoute,
  MyReportsRoute: MyReportsRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiLocalBusinessesRoute: ApiLocalBusinessesRoute,
  ApiPlaceReviewsRoute: ApiPlaceReviewsRoute,
  ApiRenovationEstimateEmailRoute: ApiRenovationEstimateEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogHowToAnalyseARightmoveListingRoute:
    BlogHowToAnalyseARightmoveListingRoute,
  ReportTokenRoute: ReportTokenRoute,
  ToolsLocalBusinessesRoute: ToolsLocalBusinessesRoute,
  ToolsRenovationCalculatorRoute: ToolsRenovationCalculatorRoute,
  ToolsStampDutyRoute: ToolsStampDutyRoute,
  BlogIndexRoute: BlogIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiPublicCronCheckExpiryRemindersRoute:
    ApiPublicCronCheckExpiryRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
